import Head from 'next/head';
import Image from 'next/image';
import Contact from '../components/Contact';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Shop from './shop';

export default function Home() {
  return (
    <div>
      <Head>
        <title> Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Welcome to Our Olshop' message='We provide various types of outfits. You can choose at will' />
      <Instagram />
      
    </div>
  );
}
